from enum import Enum, StrEnum


class UserRole(StrEnum):
    ADMIN = "ADMIN"
    MERCHANT = "MERCHANT"
    ANALYST = "ANALYST"
    CUSTOMER = "CUSTOMER"


class SessionState(StrEnum):
    ACTIVE = "ACTIVE"
    ABANDONED = "ABANDONED"
    RESCUED = "RESCUED"
    CONVERTED = "CONVERTED"
    EXPIRED = "EXPIRED"


class EventType(StrEnum):
    PAGE_VIEW = "PAGE_VIEW"
    ITEM_ADD = "ITEM_ADD"
    ITEM_REMOVE = "ITEM_REMOVE"
    CHECKOUT_START = "CHECKOUT_START"
    PAYMENT_ATTEMPT = "PAYMENT_ATTEMPT"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    CURSOR_LEAVE = "CURSOR_LEAVE"
    TAB_SWITCH = "TAB_SWITCH"
    FORM_STUCK = "FORM_STUCK"
    COUPON_APPLY = "COUPON_APPLY"
    SESSION_END = "SESSION_END"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class DiagnosisCategory(StrEnum):
    PAYMENT_FAILURE = "PAYMENT_FAILURE"
    BROWSING = "BROWSING"
    DELIVERY_DELAY = "DELIVERY_DELAY"
    SHIPPING_COST = "SHIPPING_COST"
    COUPON_WAITING = "COUPON_WAITING"
    PRICE_COMPARISON = "PRICE_COMPARISON"
    FORM_FRICTION = "FORM_FRICTION"


class DecisionAction(StrEnum):
    DO_NOTHING = "DO_NOTHING"
    RETRY_PAYMENT = "RETRY_PAYMENT"
    COD_OFFER = "COD"
    FREE_SHIPPING = "FREE_SHIPPING"
    DISCOUNT_COUPON = "COUPON"
    EXIT_POPUP = "EXIT_POPUP"
    EMAIL_RESCUE = "EMAIL"
    WHATSAPP_RESCUE = "WHATSAPP"


class PolicyViolation(StrEnum):
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    LOW_MARGIN = "LOW_MARGIN"
    CAMPAIGN_INACTIVE = "CAMPAIGN_INACTIVE"
    NO_CONSENT = "NO_CONSENT"
    TRAI_DND_BLOCKED = "TRAI_DND_BLOCKED"
    NO_WHATSAPP_OPTIN = "NO_WHATSAPP_OPTIN"


class OrderStatus(StrEnum):
    PENDING = "PENDING"
    PAID = "PAID"
    ABANDONED = "ABANDONED"
    CANCELLED = "CANCELLED"
    REFUNDED = "REFUNDED"


class PaymentStatus(StrEnum):
    INITIATED = "INITIATED"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    RETRYING = "RETRYING"
